/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResourceIndexRouteImport } from './routes/$resource/index'
import { Route as ResourceIdRouteImport } from './routes/$resource/$id'
import { Route as ResourceCreateRouteImport } from './routes/$resource/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceIndexRoute = ResourceIndexRouteImport.update({
  id: '/$resource/',
  path: '/$resource/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceIdRoute = ResourceIdRouteImport.update({
  id: '/$resource/$id',
  path: '/$resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceCreateRoute = ResourceCreateRouteImport.update({
  id: '/$resource/create',
  path: '/$resource/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$resource/$id': typeof ResourceIdRoute
  '/$resource/create': typeof ResourceCreateRoute
  '/$resource/': typeof ResourceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$resource/$id': typeof ResourceIdRoute
  '/$resource/create': typeof ResourceCreateRoute
  '/$resource': typeof ResourceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$resource/$id': typeof ResourceIdRoute
  '/$resource/create': typeof ResourceCreateRoute
  '/$resource/': typeof ResourceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/$resource/$id' | '/$resource/create' | '/$resource/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$resource/$id' | '/$resource/create' | '/$resource'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$resource/$id'
    | '/$resource/create'
    | '/$resource/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResourceIdRoute: typeof ResourceIdRoute
  ResourceCreateRoute: typeof ResourceCreateRoute
  ResourceIndexRoute: typeof ResourceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$resource/': {
      id: '/$resource/'
      path: '/$resource'
      fullPath: '/$resource/'
      preLoaderRoute: typeof ResourceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$resource/$id': {
      id: '/$resource/$id'
      path: '/$resource/$id'
      fullPath: '/$resource/$id'
      preLoaderRoute: typeof ResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$resource/create': {
      id: '/$resource/create'
      path: '/$resource/create'
      fullPath: '/$resource/create'
      preLoaderRoute: typeof ResourceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResourceIdRoute: ResourceIdRoute,
  ResourceCreateRoute: ResourceCreateRoute,
  ResourceIndexRoute: ResourceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
